# Generated by Django 5.1.3 on 2024-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
