# Generated by Django 5.1.3 on 2024-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0003_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
