# Generated by Django 5.1.3 on 2024-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0008_alter_product_created_by_alter_product_merchant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
