# Generated by Django 5.1.3 on 2024-12-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0012_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment_text",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
