# Generated by Django 5.1.3 on 2024-12-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0015_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("men", "Men"),
                    ("women", "Women"),
                    ("perfume", "Perfume"),
                    ("kids", "Kids"),
                ],
                default="men",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
