# Generated by Django 4.2 on 2024-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0018_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
