# Generated by Django 4.2 on 2024-12-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0019_document_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
    ]
