# Generated by Django 4.2 on 2024-12-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0022_rename_image_product_cloud_image_product_local_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cloud_image",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="local_image",
        ),
    ]
