# Generated by Django 4.2 on 2024-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0023_rename_cloud_image_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
