# Generated by Django 4.2 on 2024-12-30 09:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0024_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="local_image",
        ),
        migrations.AddField(
            model_name="product",
            name="cloud_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="product_image"
            ),
        ),
    ]
