# Generated by Django 4.2 on 2024-12-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0025_rename_image_product_local_image_product_cloud_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="local_image",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="cloud_image",
        ),
    ]
