# Generated by Django 4.2 on 2025-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_orderdone_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdone",
            name="order_id",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
