# Generated by Django 4.2 on 2025-01-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0030_carouselimage"),
        ("cart", "0004_alter_orderdone_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales_count", models.PositiveIntegerField(default=0)),
                ("return_count", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_data",
                        to="display.product",
                    ),
                ),
            ],
        ),
    ]
