# Generated by Django 5.1.3 on 2024-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("normal", "Normal User"), ("merchant", "Merchant")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
