# Generated by Django 5.1.3 on 2024-12-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0011_alter_watchlist_product_alter_watchlist_user"),
        ("userauth", "0002_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="watchlist_by",
            field=models.ManyToManyField(
                blank=True, related_name="watchlisted_by", to="display.product"
            ),
        ),
    ]
