# Generated by Django 5.1.3 on 2024-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_customuser_watchlist_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
